function Hd = high_pass_filter_window(Fs,Fc)
%HIGH_PASS_FILTER_WINDOW Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 9.8 and DSP System Toolbox 9.10.
% Generated on: 27-Apr-2021 16:49:32

% FIR Window Highpass filter designed using the FIR1 function.

% All frequency values are in Hz.
%Fs = 135;  % Sampling Frequency

N    = 1;        % Order
%Fc   = 0.01;     % Cutoff Frequency
flag = 'scale';  % Sampling Flag
Beta = 0.5;      % Window Parameter

% Create the window vector for the design algorithm.
win = kaiser(N+1, Beta);

% Calculate the coefficients using the FIR1 function.
b  = fir1(N, Fc/(Fs/2), 'high', win, flag, 'h');
Hd = dfilt.dffir(b);

% [EOF]
