function Hd = low_pass_filter_window(Fs,Fc)
%LOW_PASS_FILTER_WINDOW Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 9.8 and DSP System Toolbox 9.10.
% Generated on: 27-Apr-2021 16:39:00

% FIR Window Lowpass filter designed using the FIR1 function.

% All frequency values are in Hz.
%Fs = 135;  % Sampling Frequency

N    = 10;       % Order
%Fc   = 5;        % Cutoff Frequency
flag = 'scale';  % Sampling Flag
Beta = 0.5;      % Window Parameter

% Create the window vector for the design algorithm.
win = kaiser(N+1, Beta);

% Calculate the coefficients using the FIR1 function.
b  = fir1(N, Fc/(Fs/2), 'low', win, flag);
Hd = dfilt.dffir(b);

% [EOF]
