function Hd = low_pass_filter(Fs,Fc)
%LOW_PASS_FILTER Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 9.8 and DSP System Toolbox 9.10.
% Generated on: 21-Feb-2021 13:27:00

% FIR constrained least-squares Lowpass filter designed using the FIRCLS
% function.

% All frequency values are in Hz.
%Fs = 32;  % Sampling Frequency

N      = 20;   % Order
%Fc     = 2;    % Cutoff Frequency
DpassU = 0.1;  % Upper Passband Ripple
DpassL = 0.1;  % Lower Passband Ripple
DstopU = 0.1;  % Upper Stopband Attenuation
DstopL = 0.1;  % Lower Stopband Attenuation

% Calculate the coefficients using the FIRCLS function.
b  = fircls(N, [0 Fc Fs/2]/(Fs/2), [1 0], [1+DpassU DstopU], [1-DpassL ...
            -DstopL]);
Hd = dfilt.dffir(b);

% [EOF]
