function Hd = band_high_pass_filter(Fs,Fstop,Fpass)
%BAND_HIGH_PASS_FILTER Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 9.8 and DSP System Toolbox 9.10.
% Generated on: 18-Feb-2021 19:57:38

% Constrained Band Equiripple FIR Highpass filter designed using the
% FIRCBAND function.

% All frequency values are in Hz.
%Fs = 512;  % Sampling Frequency

N     = 10;    % Order
%Fstop = 0.05;  % Stopband Frequency
%Fpass = 0.5;   % Passband Frequency
Wstop = 1;     % Stopband Weight
Wpass = 1;     % Passband Weight
dens  = 20;    % Density Factor

% Calculate the coefficients using the FIRCBAND function.
b  = fircband(N, [0 Fstop Fpass Fs/2]/(Fs/2), [0 0 1 1], [Wstop Wpass], ...
              {dens});
Hd = dfilt.dffir(b);

% [EOF]
