function Hd = band_low_pass_filter(Fs,Fpass,Fstop)
%BAND_LOW_PASS_FILTER Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 9.8 and DSP System Toolbox 9.10.
% Generated on: 18-Feb-2021 19:50:25

% Constrained Band Equiripple FIR Lowpass filter designed using the
% FIRCBAND function.

% All frequency values are in Hz.
%Fs = 512;  % Sampling Frequency

N     = 10;    % Order
%Fpass = 0.05;  % Passband Frequency
%Fstop = 40;    % Stopband Frequency
Wpass = 1;     % Passband Weight
Wstop = 1;     % Stopband Weight
dens  = 20;    % Density Factor

% Calculate the coefficients using the FIRCBAND function.
b  = fircband(N, [0 Fpass Fstop Fs/2]/(Fs/2), [1 1 0 0], [Wpass Wstop], ...
              {dens});
Hd = dfilt.dffir(b);

% [EOF]
